/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;
import newpackage.Config;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author ADMIN
 */
public class Memo extends javax.swing.JFrame {
     private Config log = new Config();
     private boolean caraUp = false;
     private ImageIcon im1;
     private ImageIcon im2;
     private JButton[] pbtn = new JButton[2];
     private boolean primerc = false;
     private int puntaje = 0;
    

    /**
     * Creates new form Memo
     */
    public Memo() {
        initComponents();
        setCartitas();
    }
    private void setCartitas() {
        int[] numbers = log.getCardNumbers();
        
        B1.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[0]+".png")));
        B2.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[1]+".png")));
        B3.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[2]+".png")));
        B4.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[3]+".png")));
        B5.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[4]+".png")));
        B6.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[5]+".png")));
        B7.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[6]+".png")));
        B8.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[7]+".png")));
        B9.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[8]+".png")));
        B10.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[9]+".png")));
        B11.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[10]+".png")));
        B12.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[11]+".png")));
        B13.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[12]+".png")));
        B14.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[13]+".png")));
        B15.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[14]+".png")));
        B16.setDisabledIcon(new ImageIcon(getClass().getResource("../proyecto/"+numbers[15]+".png")));
     
    } 
    private void btnEnabled(JButton btn) {
        
        if(!caraUp) {
            btn.setEnabled(false);
            im1 = (ImageIcon) btn.getDisabledIcon();
            pbtn[0] = btn;
            caraUp = true;
            primerc = false;
        }
        else {
            btn.setEnabled(false);
            im2 = (ImageIcon) btn.getDisabledIcon();
            pbtn[1] = btn;
            primerc = true;
            puntaje += 20;
            pregwin();
        }
    }   
    private void compare() {
        if(caraUp && primerc) {
            
            if(im1.getDescription().compareTo(im2.getDescription()) != 0) {
                pbtn[0].setEnabled(true);
                pbtn[1].setEnabled(true);
                if(puntaje > 10 ) puntaje -= 10;
            }
            caraUp = false;
        }
    }
    private void reiniciar() {
        
        B1.setEnabled(true);
        B2.setEnabled(true);
        B3.setEnabled(true);
        B4.setEnabled(true);
        B5.setEnabled(true);
        B6.setEnabled(true);
        B7.setEnabled(true);
        B8.setEnabled(true);
        B9.setEnabled(true);
        B10.setEnabled(true);
        B11.setEnabled(true);
        B12.setEnabled(true);
        B13.setEnabled(true);
        B14.setEnabled(true);
        B15.setEnabled(true);
        B16.setEnabled(true);
       
        
        primerc = false;
        caraUp = false;
        puntaje = 0;
    }
    
    private void pregwin() {
        if(!B1.isEnabled() && !B2.isEnabled() && !B3.isEnabled() && !B4.isEnabled() && !B5.isEnabled() && !B6.isEnabled() && 
                !B7.isEnabled() && !B8.isEnabled() && !B9.isEnabled() &&!B10.isEnabled() &&!B11.isEnabled() &&!B12.isEnabled() 
                &&!B13.isEnabled()&&!B14.isEnabled()&&!B15.isEnabled()&&!B16.isEnabled()) {
            jLabel1.setText("Jueguin terminado");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        B13 = new javax.swing.JButton();
        B14 = new javax.swing.JButton();
        B15 = new javax.swing.JButton();
        B16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B1.setBorder(null);
        B1.setBorderPainted(false);
        B1.setContentAreaFilled(false);
        B1.setFocusable(false);
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B1MouseExited(evt);
            }
        });
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B2.setBorder(null);
        B2.setBorderPainted(false);
        B2.setContentAreaFilled(false);
        B2.setFocusable(false);
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B2MouseExited(evt);
            }
        });
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B3.setBorder(null);
        B3.setBorderPainted(false);
        B3.setContentAreaFilled(false);
        B3.setFocusable(false);
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B3MouseExited(evt);
            }
        });
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B4.setBorder(null);
        B4.setBorderPainted(false);
        B4.setContentAreaFilled(false);
        B4.setFocusable(false);
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B4MouseExited(evt);
            }
        });
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B5.setBorder(null);
        B5.setBorderPainted(false);
        B5.setContentAreaFilled(false);
        B5.setFocusable(false);
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B5MouseExited(evt);
            }
        });
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B6.setBorder(null);
        B6.setBorderPainted(false);
        B6.setContentAreaFilled(false);
        B6.setFocusable(false);
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B6MouseExited(evt);
            }
        });
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B7.setBorder(null);
        B7.setBorderPainted(false);
        B7.setContentAreaFilled(false);
        B7.setFocusable(false);
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B7MouseExited(evt);
            }
        });
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B8.setBorder(null);
        B8.setBorderPainted(false);
        B8.setContentAreaFilled(false);
        B8.setFocusable(false);
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B8MouseExited(evt);
            }
        });
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B9.setBorder(null);
        B9.setBorderPainted(false);
        B9.setContentAreaFilled(false);
        B9.setFocusable(false);
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B9MouseExited(evt);
            }
        });
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        B10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B10.setBorder(null);
        B10.setBorderPainted(false);
        B10.setContentAreaFilled(false);
        B10.setFocusable(false);
        B10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B10MouseExited(evt);
            }
        });
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });

        B11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B11.setBorder(null);
        B11.setBorderPainted(false);
        B11.setContentAreaFilled(false);
        B11.setFocusable(false);
        B11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B11MouseExited(evt);
            }
        });
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });

        B12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B12.setBorder(null);
        B12.setBorderPainted(false);
        B12.setContentAreaFilled(false);
        B12.setFocusable(false);
        B12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B12MouseExited(evt);
            }
        });
        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });

        B13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B13.setBorder(null);
        B13.setBorderPainted(false);
        B13.setContentAreaFilled(false);
        B13.setFocusable(false);
        B13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B13MouseExited(evt);
            }
        });
        B13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B13ActionPerformed(evt);
            }
        });

        B14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B14.setBorder(null);
        B14.setBorderPainted(false);
        B14.setContentAreaFilled(false);
        B14.setFocusable(false);
        B14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B14MouseExited(evt);
            }
        });
        B14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B14ActionPerformed(evt);
            }
        });

        B15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B15.setBorder(null);
        B15.setBorderPainted(false);
        B15.setContentAreaFilled(false);
        B15.setFocusable(false);
        B15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B15MouseExited(evt);
            }
        });
        B15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B15ActionPerformed(evt);
            }
        });

        B16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/0.png"))); // NOI18N
        B16.setBorder(null);
        B16.setBorderPainted(false);
        B16.setContentAreaFilled(false);
        B16.setFocusable(false);
        B16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B16MouseExited(evt);
            }
        });
        B16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B16ActionPerformed(evt);
            }
        });

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(B13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(B14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(B15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(B16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1)
                    .addComponent(B2)
                    .addComponent(B3)
                    .addComponent(B4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B5)
                    .addComponent(B6)
                    .addComponent(B7)
                    .addComponent(B8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B9)
                    .addComponent(B10)
                    .addComponent(B11)
                    .addComponent(B12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B13)
                    .addComponent(B14)
                    .addComponent(B15)
                    .addComponent(B16))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void B1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B1MouseExited

    private void B2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B2MouseExited

    private void B3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B3MouseExited

    private void B4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B4MouseExited

    private void B5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B5MouseExited

    private void B6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B6MouseExited

    private void B7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B7MouseExited

    private void B8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B8MouseExited

    private void B9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B9MouseExited

    private void B10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B10MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B10MouseExited

    private void B11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B11MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B11MouseExited

    private void B12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B12MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B12MouseExited

    private void B13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B13MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B13MouseExited

    private void B14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B14MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B14MouseExited

    private void B15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B15MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B15MouseExited

    private void B16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B16MouseExited
        compare();// TODO add your handling code here:
    }//GEN-LAST:event_B16MouseExited

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        btnEnabled(B1); // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        btnEnabled(B2);// TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        btnEnabled(B3); // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        btnEnabled(B4);// TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        btnEnabled(B5); // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        btnEnabled(B6);// TODO add your handling code here:
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        btnEnabled(B7);// TODO add your handling code here:
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        btnEnabled(B8);// TODO add your handling code here:
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        btnEnabled(B9);// TODO add your handling code here:
    }//GEN-LAST:event_B9ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
        btnEnabled(B10);// TODO add your handling code here:
    }//GEN-LAST:event_B10ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
        btnEnabled(B11);// TODO add your handling code here:
    }//GEN-LAST:event_B11ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed
        btnEnabled(B12);// TODO add your handling code here:
    }//GEN-LAST:event_B12ActionPerformed

    private void B13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B13ActionPerformed
        btnEnabled(B13);// TODO add your handling code here:
    }//GEN-LAST:event_B13ActionPerformed

    private void B14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B14ActionPerformed
        btnEnabled(B14);// TODO add your handling code here:
    }//GEN-LAST:event_B14ActionPerformed

    private void B15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B15ActionPerformed
        btnEnabled(B15);// TODO add your handling code here:
    }//GEN-LAST:event_B15ActionPerformed

    private void B16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B16ActionPerformed
        btnEnabled(B16);// TODO add your handling code here:
    }//GEN-LAST:event_B16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reiniciar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Memo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B13;
    private javax.swing.JButton B14;
    private javax.swing.JButton B15;
    private javax.swing.JButton B16;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
